# Generated by Django 3.0.5 on 2021-05-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('numofemployees', models.IntegerField(db_column='NumOfEmployees')),
                ('branchid', models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Branch')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=255, null=True)),
                ('exp', models.FloatField(db_column='Exp')),
                ('departmentid', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('taxid', models.CharField(blank=True, db_column='TaxId', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('price', models.FloatField(db_column='Price')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
                ('numinbranch', models.IntegerField(db_column='NumInBranch')),
                ('branchid', models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Branch')),
                ('partnerid', models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Partner')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Salarytable',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('total', models.FloatField(db_column='Total')),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'salarytable',
            },
        ),
        migrations.CreateModel(
            name='Statisticrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('num', models.FloatField(db_column='Num')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
            ],
            options={
                'db_table': 'statisticrec',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('created', models.DateField(blank=True, db_column='Created', null=True)),
                ('team', models.IntegerField(db_column='Team')),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
                ('branchid', models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Branch')),
            ],
            options={
                'db_table': 'accountant',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billtype', models.CharField(blank=True, db_column='BillType', max_length=255, null=True)),
                ('tax', models.TextField(db_column='Tax')),
                ('documentid', models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Document')),
                ('partnerid', models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Partner')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='Chiefmanager',
            fields=[
                ('cardid', models.CharField(blank=True, db_column='CardID', max_length=255, null=True)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
            ],
            options={
                'db_table': 'chiefmanager',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('created', models.DateField(blank=True, db_column='Created', null=True)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
                ('branchid', models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Branch')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipttype', models.CharField(blank=True, db_column='ReceiptType', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('documentid', models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Document')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='Taxinvoice',
            fields=[
                ('taxtype', models.CharField(blank=True, db_column='TaxType', max_length=255, null=True)),
                ('percentage', models.FloatField(db_column='Percentage')),
                ('attachedto', models.CharField(blank=True, db_column='AttachedTo', max_length=255, null=True)),
                ('documentid', models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Document')),
            ],
            options={
                'db_table': 'taxinvoice',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('term', models.CharField(blank=True, db_column='Term', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
                ('detail', models.CharField(blank=True, db_column='Detail', max_length=255, null=True)),
                ('balance', models.FloatField(db_column='Balance')),
                ('tax', models.FloatField(db_column='Tax')),
                ('statisticrecid', models.ForeignKey(db_column='StatisticRecID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Statisticrec')),
            ],
            options={
                'db_table': 'summary',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='Amount')),
                ('adding', models.FloatField(db_column='Adding')),
                ('deducting', models.FloatField(db_column='Deducting')),
                ('sum', models.FloatField(db_column='Sum')),
                ('coef', models.FloatField(db_column='Coef')),
                ('reward', models.FloatField(db_column='Reward')),
                ('employeeid', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Employee')),
                ('salarytableid', models.ForeignKey(db_column='SalaryTableID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Salarytable')),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.AddField(
            model_name='statisticrec',
            name='chiefmanageruserid',
            field=models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Chiefmanager'),
        ),
        migrations.AddField(
            model_name='statisticrec',
            name='manageruserid',
            field=models.ForeignKey(db_column='ManagerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Manager'),
        ),
        migrations.AddField(
            model_name='salarytable',
            name='accountantuserid',
            field=models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Accountant'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('sum', models.FloatField(db_column='Sum')),
                ('accountantuserid', models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Accountant')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Loanrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('chiefmanageruserid', models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Chiefmanager')),
            ],
            options={
                'db_table': 'loanrec',
            },
        ),
        migrations.CreateModel(
            name='Lendrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('partnerid', models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Partner')),
                ('chiefmanageruserid', models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Chiefmanager')),
            ],
            options={
                'db_table': 'lendrec',
            },
        ),
        migrations.CreateModel(
            name='Investmentrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('chiefmanageruserid', models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Chiefmanager')),
            ],
            options={
                'db_table': 'investmentrec',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='accountantuserid',
            field=models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Accountant'),
        ),
        migrations.CreateModel(
            name='Balancerec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('accountantuserid', models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Accountant')),
            ],
            options={
                'db_table': 'balancerec',
            },
        ),
        migrations.CreateModel(
            name='ProductBill',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Product')),
                ('billdocumentid', models.ForeignKey(db_column='BillDocumentID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Bill')),
            ],
            options={
                'db_table': 'product_bill',
                'unique_together': {('productid', 'billdocumentid')},
            },
        ),
    ]
