# Generated by Django 3.0.5 on 2021-05-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='branchid',
            field=models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.CASCADE, to='api.Branch'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='userid',
            field=models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.User'),
        ),
        migrations.AlterField(
            model_name='balancerec',
            name='accountantuserid',
            field=models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Accountant'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='documentid',
            field=models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Document'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='partnerid',
            field=models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.CASCADE, to='api.Partner'),
        ),
        migrations.AlterField(
            model_name='chiefmanager',
            name='userid',
            field=models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.User'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branchid',
            field=models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.CASCADE, to='api.Branch'),
        ),
        migrations.AlterField(
            model_name='document',
            name='accountantuserid',
            field=models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Accountant'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departmentid',
            field=models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
        ),
        migrations.AlterField(
            model_name='investmentrec',
            name='chiefmanageruserid',
            field=models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Chiefmanager'),
        ),
        migrations.AlterField(
            model_name='lendrec',
            name='chiefmanageruserid',
            field=models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Chiefmanager'),
        ),
        migrations.AlterField(
            model_name='lendrec',
            name='partnerid',
            field=models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.CASCADE, to='api.Partner'),
        ),
        migrations.AlterField(
            model_name='loanrec',
            name='chiefmanageruserid',
            field=models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Chiefmanager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='branchid',
            field=models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.CASCADE, to='api.Branch'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='userid',
            field=models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='branchid',
            field=models.ForeignKey(db_column='BranchID', on_delete=django.db.models.deletion.CASCADE, to='api.Branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnerid',
            field=models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.CASCADE, to='api.Partner'),
        ),
        migrations.AlterField(
            model_name='productbill',
            name='billdocumentid',
            field=models.ForeignKey(db_column='BillDocumentID', on_delete=django.db.models.deletion.CASCADE, to='api.Bill'),
        ),
        migrations.AlterField(
            model_name='productbill',
            name='productid',
            field=models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Product'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='documentid',
            field=models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Document'),
        ),
        migrations.AlterField(
            model_name='report',
            name='accountantuserid',
            field=models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Accountant'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salarytableid',
            field=models.ForeignKey(db_column='SalaryTableID', on_delete=django.db.models.deletion.CASCADE, to='api.Salarytable'),
        ),
        migrations.AlterField(
            model_name='salarytable',
            name='accountantuserid',
            field=models.ForeignKey(db_column='AccountantUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Accountant'),
        ),
        migrations.AlterField(
            model_name='statisticrec',
            name='chiefmanageruserid',
            field=models.ForeignKey(db_column='ChiefManagerUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Chiefmanager'),
        ),
        migrations.AlterField(
            model_name='statisticrec',
            name='manageruserid',
            field=models.ForeignKey(db_column='ManagerUserID', on_delete=django.db.models.deletion.CASCADE, to='api.Manager'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='statisticrecid',
            field=models.ForeignKey(db_column='StatisticRecID', on_delete=django.db.models.deletion.CASCADE, to='api.Statisticrec'),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='documentid',
            field=models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Document'),
        ),
    ]
