# Generated by Django 3.0.5 on 2021-05-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210410_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
