# Generated by Django 3.0.5 on 2021-05-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancerec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
            ],
            options={
                'db_table': 'balancerec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('numofemployees', models.IntegerField(db_column='NumOfEmployees')),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('content', models.CharField(blank=True, db_column='Content', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=255, null=True)),
                ('exp', models.FloatField(db_column='Exp')),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investmentrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
            ],
            options={
                'db_table': 'investmentrec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lendrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'lendrec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loanrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('amount', models.FloatField(db_column='Amount')),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'loanrec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('taxid', models.CharField(blank=True, db_column='TaxId', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
            ],
            options={
                'db_table': 'partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=255, null=True)),
                ('price', models.FloatField(db_column='Price')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=255, null=True)),
                ('numinbranch', models.IntegerField(db_column='NumInBranch')),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('sum', models.FloatField(db_column='Sum')),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='Amount')),
                ('adding', models.FloatField(db_column='Adding')),
                ('deducting', models.FloatField(db_column='Deducting')),
                ('sum', models.FloatField(db_column='Sum')),
                ('coef', models.FloatField(db_column='Coef')),
                ('reward', models.FloatField(db_column='Reward')),
            ],
            options={
                'db_table': 'salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salarytable',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('total', models.FloatField(db_column='Total')),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'salarytable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statisticrec',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('time', models.DateField(blank=True, db_column='Time', null=True)),
                ('num', models.FloatField(db_column='Num')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
            ],
            options={
                'db_table': 'statisticrec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('term', models.CharField(blank=True, db_column='Term', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
                ('detail', models.CharField(blank=True, db_column='Detail', max_length=255, null=True)),
                ('balance', models.FloatField(db_column='Balance')),
                ('tax', models.FloatField(db_column='Tax')),
            ],
            options={
                'db_table': 'summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('created', models.DateField(blank=True, db_column='Created', null=True)),
                ('team', models.IntegerField(db_column='Team')),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
            ],
            options={
                'db_table': 'accountant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billtype', models.CharField(blank=True, db_column='BillType', max_length=255, null=True)),
                ('tax', models.TextField(db_column='Tax')),
                ('documentid', models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Document')),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chiefmanager',
            fields=[
                ('cardid', models.CharField(blank=True, db_column='CardID', max_length=255, null=True)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
            ],
            options={
                'db_table': 'chiefmanager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('created', models.DateField(blank=True, db_column='Created', null=True)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.User')),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBill',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Product')),
            ],
            options={
                'db_table': 'product_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipttype', models.CharField(blank=True, db_column='ReceiptType', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('documentid', models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Document')),
            ],
            options={
                'db_table': 'receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxinvoice',
            fields=[
                ('taxtype', models.CharField(blank=True, db_column='TaxType', max_length=255, null=True)),
                ('percentage', models.FloatField(db_column='Percentage')),
                ('attachedto', models.CharField(blank=True, db_column='AttachedTo', max_length=255, null=True)),
                ('documentid', models.OneToOneField(db_column='DocumentID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Document')),
            ],
            options={
                'db_table': 'taxinvoice',
                'managed': False,
            },
        ),
    ]
